# Build stage
FROM node:18-alpine AS build
WORKDIR /app

COPY trip-planner-front/package*.json ./
RUN npm ci

COPY trip-planner-front/ .
RUN npm run build

# Production stage
FROM node:18-alpine AS final
WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/dist ./dist

EXPOSE 3000

ENV NODE_ENV=production
CMD ["serve", "-s", "dist", "-l", "3000"]