services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: trip-planner-db
    environment:
      SA_PASSWORD: "nq0/^t&[vD:6.HawN&%Ul!@#"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - trip-planner-network
    restart: unless-stopped

  # Trip Planner API
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: trip-planner-api
    expose:
      - "5000"
    volumes:
      - uploads-data:/app/wwwroot/uploads
      - avatars-data:/app/wwwroot/avatars
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:5000"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      ConnectionStrings__DefaultConnection: "Data Source=sqlserver;Initial Catalog=TripPlanner;User ID=sa;Password=nq0/^t&[vD:6.HawN&%Ul!@#;TrustServerCertificate=True; MultipleActiveResultSets=True; Max Pool Size=1000; Connection Timeout=30;"
    depends_on:
      - sqlserver
    networks:
      - trip-planner-network
    restart: unless-stopped
    stdin_open: true
    tty: false
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"


    # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: trip-planner-frontend
    expose:
      - "3000"
    environment:
      - VITE_API_URL=/api
    depends_on:
      - api
    networks:
      - trip-planner-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # Nginx Reverse Proxy
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: trip-planner-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - api
    networks:
      - trip-planner-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  sqlserver-data:
  uploads-data:
  avatars-data:


networks:
  trip-planner-network:
    driver: bridge
